# fly.toml app configuration file generated for twilio-v2v on 2024-08-03T04:55:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twilio-v2v'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5515
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  TWILIO_V2V_PORT = 5515